sudo: false
language: go
go:
- tip
addons:
  apt:
    packages:
    - rpm
    - pandoc
before_install:
- gem install fpm
- gem install package_cloud
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
script:
  - make test
after_success:
  - make coverage && $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci
deploy:
  provider: script
  script: make deploy-packages
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: STk08ygMm5ua4iCaPYa5VR9W/H1NMzi0w170jSzCCu/bpHuOsGK56N+9h+U9sJJ49bhF+mGbjDicY0I4oJwSIpxBzY9ATycsAgagUUD1V7QRfapISHzPs3PfHmfbGwm0fkrdNcSUBKxt5sZm2gCZYkP4ToTGMVL6p9TF1CO/Q7rdO9NrOwO5adcv5f6BOBGOGOW9KFsfYOpvO2fHw2SSw0lYpQDZlczpWg5bh++zWWsIzW1JM9IQcROXetccIE2+5uyX1Lz+rrBbfhFiiB+inkUm0t8DMXc3augveWfcgdbg/55isZxTwdiFc5YD/kQ84Cr4/HzC/Ol6gozfOL5+yrtTd3xc3Lxk/u+CLzc/zMPiQY/sRoTUa9MkiMCsTQSjvPGXwm7MiW/Ly4/boG5BoSxMGVjQlVe7P1GrJE2yqELLZSkZUO5cYy37jx4kc0aLAc+j0VTNdcZ5Fi3vAAmv3nKxOirB/r8Pp/r8MJRtbCBJ+0s9G+tuSXiP/2zzVjUHaup0b3ZjbTEzaEiqX95V6b7Iqj2xmdD7odbVhghnLPe0iVG3hmP8ZbOKz+aMwOXlcyUnji5UpDuWFqT/459zVJxhKn/lwIfpnI4pNDr1Jb23nEGI9VE7LrBeCv/65gJ8tyKqd3fMtV6ze+8cFHXnOeFtAvU5FE3ZHI2+0mTG0N8=
